# Site Settings
theme: jekyll-theme-slate
title: Greg Hamilton's Homepage
description: Senior Data Scientist and Recovering Management Consultant

# Author Information
author:
  name: Greg Hamilton
  email: # Add your email if desired
  github: hreggramDS
  linkedin: # Add your LinkedIn username if desired

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  pipelines:
    output: true
    permalink: /pipelines/:name/
  team:
    output: false
    permalink: /team/:name/

# Collection Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Greg Hamilton"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pipelines"
    values:
      layout: "pipeline"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - README.md
  - SITE_DESIGN.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
